/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

//// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiYoutubeCallbackRouteImport } from './routes/api/youtube/callback'
import { Route as ApiYoutubeMeRouteImport } from './routes/api/youtube/me'
import { Route as ApiYoutubeLogoutRouteImport } from './routes/api/youtube/logout'
import { Route as ApiYoutubeStartRouteImport } from './routes/api/youtube/start'
import { Route as ApiPlusGrantRouteImport } from './routes/api/plus/grant'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeCallbackRoute = ApiYoutubeCallbackRouteImport.update({
  id: '/api/youtube/callback',
  path: '/api/youtube/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeMeRoute = ApiYoutubeMeRouteImport.update({
  id: '/api/youtube/me',
  path: '/api/youtube/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeLogoutRoute = ApiYoutubeLogoutRouteImport.update({
  id: '/api/youtube/logout',
  path: '/api/youtube/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeStartRoute = ApiYoutubeStartRouteImport.update({
  id: '/api/youtube/start',
  path: '/api/youtube/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlusGrantRoute = ApiPlusGrantRouteImport.update({
  id: '/api/plus/grant',
  path: '/api/plus/grant',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/youtube/callback': typeof ApiYoutubeCallbackRoute
  '/api/youtube/me': typeof ApiYoutubeMeRoute
  '/api/youtube/logout': typeof ApiYoutubeLogoutRoute
  '/api/youtube/start': typeof ApiYoutubeStartRoute
  '/api/plus/grant': typeof ApiPlusGrantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/youtube/callback': typeof ApiYoutubeCallbackRoute
  '/api/youtube/me': typeof ApiYoutubeMeRoute
  '/api/youtube/logout': typeof ApiYoutubeLogoutRoute
  '/api/youtube/start': typeof ApiYoutubeStartRoute
  '/api/plus/grant': typeof ApiPlusGrantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/youtube/callback': typeof ApiYoutubeCallbackRoute
  '/api/youtube/me': typeof ApiYoutubeMeRoute
  '/api/youtube/logout': typeof ApiYoutubeLogoutRoute
  '/api/youtube/start': typeof ApiYoutubeStartRoute
  '/api/plus/grant': typeof ApiPlusGrantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/youtube/callback' | '/api/youtube/me' | '/api/youtube/logout' | '/api/youtube/start' | '/api/plus/grant'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/youtube/callback' | '/api/youtube/me' | '/api/youtube/logout' | '/api/youtube/start' | '/api/plus/grant'
  id:
    | '__root__'
    | '/'
    | '/api/youtube/callback'
    | '/api/youtube/me'
    | '/api/youtube/logout'
    | '/api/youtube/start'
    | '/api/plus/grant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiYoutubeCallbackRoute: typeof ApiYoutubeCallbackRoute
  ApiYoutubeMeRoute: typeof ApiYoutubeMeRoute
  ApiYoutubeLogoutRoute: typeof ApiYoutubeLogoutRoute
  ApiYoutubeStartRoute: typeof ApiYoutubeStartRoute
  ApiPlusGrantRoute: typeof ApiPlusGrantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/callback': {
      id: '/api/youtube/callback'
      path: '/api/youtube/callback'
      fullPath: '/api/youtube/callback'
      preLoaderRoute: typeof ApiYoutubeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/me': {
      id: '/api/youtube/me'
      path: '/api/youtube/me'
      fullPath: '/api/youtube/me'
      preLoaderRoute: typeof ApiYoutubeMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/logout': {
      id: '/api/youtube/logout'
      path: '/api/youtube/logout'
      fullPath: '/api/youtube/logout'
      preLoaderRoute: typeof ApiYoutubeLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/start': {
      id: '/api/youtube/start'
      path: '/api/youtube/start'
      fullPath: '/api/youtube/start'
      preLoaderRoute: typeof ApiYoutubeStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plus/grant': {
      id: '/api/plus/grant'
      path: '/api/plus/grant'
      fullPath: '/api/plus/grant'
      preLoaderRoute: typeof ApiPlusGrantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiYoutubeCallbackRoute: ApiYoutubeCallbackRoute,
  ApiYoutubeMeRoute: ApiYoutubeMeRoute,
  ApiYoutubeLogoutRoute: ApiYoutubeLogoutRoute,
  ApiYoutubeStartRoute: ApiYoutubeStartRoute,
  ApiPlusGrantRoute: ApiPlusGrantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()


import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
