/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiPitchRouteImport } from './routes/api/pitch'
import { Route as ApiReferralsRouteImport } from './routes/api/referrals'
import { Route as ApiFirebaseConfigRouteImport } from './routes/api/firebase/config'
import { Route as ApiFirebaseCustomTokenRouteImport } from './routes/api/firebase/custom-token'
import { Route as ApiFirebaseSessionRouteImport } from './routes/api/firebase/session'
import { Route as ApiPlusGrantRouteImport } from './routes/api/plus/grant'
import { Route as ApiPlusStatusRouteImport } from './routes/api/plus/status'
import { Route as ApiProfileSyncRouteImport } from './routes/api/profile/sync'
import { Route as ApiStripeCheckoutRouteImport } from './routes/api/stripe/checkout'
import { Route as ApiStripeConfirmRouteImport } from './routes/api/stripe/confirm'
import { Route as ApiStripeModeRouteImport } from './routes/api/stripe/mode'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiYoutubeCallbackRouteImport } from './routes/api/youtube/callback'
import { Route as ApiYoutubeLogoutRouteImport } from './routes/api/youtube/logout'
import { Route as ApiYoutubeMeRouteImport } from './routes/api/youtube/me'
import { Route as ApiYoutubeStartRouteImport } from './routes/api/youtube/start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPitchRoute = ApiPitchRouteImport.update({
  id: '/api/pitch',
  path: '/api/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferralsRoute = ApiReferralsRouteImport.update({
  id: '/api/referrals',
  path: '/api/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFirebaseConfigRoute = ApiFirebaseConfigRouteImport.update({
  id: '/api/firebase/config',
  path: '/api/firebase/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFirebaseCustomTokenRoute = ApiFirebaseCustomTokenRouteImport.update({
  id: '/api/firebase/custom-token',
  path: '/api/firebase/custom-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFirebaseSessionRoute = ApiFirebaseSessionRouteImport.update({
  id: '/api/firebase/session',
  path: '/api/firebase/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlusGrantRoute = ApiPlusGrantRouteImport.update({
  id: '/api/plus/grant',
  path: '/api/plus/grant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlusStatusRoute = ApiPlusStatusRouteImport.update({
  id: '/api/plus/status',
  path: '/api/plus/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileSyncRoute = ApiProfileSyncRouteImport.update({
  id: '/api/profile/sync',
  path: '/api/profile/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeCheckoutRoute = ApiStripeCheckoutRouteImport.update({
  id: '/api/stripe/checkout',
  path: '/api/stripe/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeConfirmRoute = ApiStripeConfirmRouteImport.update({
  id: '/api/stripe/confirm',
  path: '/api/stripe/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeModeRoute = ApiStripeModeRouteImport.update({
  id: '/api/stripe/mode',
  path: '/api/stripe/mode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeCallbackRoute = ApiYoutubeCallbackRouteImport.update({
  id: '/api/youtube/callback',
  path: '/api/youtube/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeLogoutRoute = ApiYoutubeLogoutRouteImport.update({
  id: '/api/youtube/logout',
  path: '/api/youtube/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeMeRoute = ApiYoutubeMeRouteImport.update({
  id: '/api/youtube/me',
  path: '/api/youtube/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeStartRoute = ApiYoutubeStartRouteImport.update({
  id: '/api/youtube/start',
  path: '/api/youtube/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/pitch': typeof ApiPitchRoute
  '/api/referrals': typeof ApiReferralsRoute
  '/api/firebase/config': typeof ApiFirebaseConfigRoute
  '/api/firebase/custom-token': typeof ApiFirebaseCustomTokenRoute
  '/api/firebase/session': typeof ApiFirebaseSessionRoute
  '/api/plus/grant': typeof ApiPlusGrantRoute
  '/api/plus/status': typeof ApiPlusStatusRoute
  '/api/profile/sync': typeof ApiProfileSyncRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/confirm': typeof ApiStripeConfirmRoute
  '/api/stripe/mode': typeof ApiStripeModeRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/youtube/callback': typeof ApiYoutubeCallbackRoute
  '/api/youtube/logout': typeof ApiYoutubeLogoutRoute
  '/api/youtube/me': typeof ApiYoutubeMeRoute
  '/api/youtube/start': typeof ApiYoutubeStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/pitch': typeof ApiPitchRoute
  '/api/referrals': typeof ApiReferralsRoute
  '/api/firebase/config': typeof ApiFirebaseConfigRoute
  '/api/firebase/custom-token': typeof ApiFirebaseCustomTokenRoute
  '/api/firebase/session': typeof ApiFirebaseSessionRoute
  '/api/plus/grant': typeof ApiPlusGrantRoute
  '/api/plus/status': typeof ApiPlusStatusRoute
  '/api/profile/sync': typeof ApiProfileSyncRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/confirm': typeof ApiStripeConfirmRoute
  '/api/stripe/mode': typeof ApiStripeModeRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/youtube/callback': typeof ApiYoutubeCallbackRoute
  '/api/youtube/logout': typeof ApiYoutubeLogoutRoute
  '/api/youtube/me': typeof ApiYoutubeMeRoute
  '/api/youtube/start': typeof ApiYoutubeStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/pitch': typeof ApiPitchRoute
  '/api/referrals': typeof ApiReferralsRoute
  '/api/firebase/config': typeof ApiFirebaseConfigRoute
  '/api/firebase/custom-token': typeof ApiFirebaseCustomTokenRoute
  '/api/firebase/session': typeof ApiFirebaseSessionRoute
  '/api/plus/grant': typeof ApiPlusGrantRoute
  '/api/plus/status': typeof ApiPlusStatusRoute
  '/api/profile/sync': typeof ApiProfileSyncRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/confirm': typeof ApiStripeConfirmRoute
  '/api/stripe/mode': typeof ApiStripeModeRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/youtube/callback': typeof ApiYoutubeCallbackRoute
  '/api/youtube/logout': typeof ApiYoutubeLogoutRoute
  '/api/youtube/me': typeof ApiYoutubeMeRoute
  '/api/youtube/start': typeof ApiYoutubeStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/api/pitch'
    | '/api/referrals'
    | '/api/firebase/config'
    | '/api/firebase/custom-token'
    | '/api/firebase/session'
    | '/api/plus/grant'
    | '/api/plus/status'
    | '/api/profile/sync'
    | '/api/stripe/checkout'
    | '/api/stripe/confirm'
    | '/api/stripe/mode'
    | '/api/stripe/webhook'
    | '/api/youtube/callback'
    | '/api/youtube/logout'
    | '/api/youtube/me'
    | '/api/youtube/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/api/pitch'
    | '/api/referrals'
    | '/api/firebase/config'
    | '/api/firebase/custom-token'
    | '/api/firebase/session'
    | '/api/plus/grant'
    | '/api/plus/status'
    | '/api/profile/sync'
    | '/api/stripe/checkout'
    | '/api/stripe/confirm'
    | '/api/stripe/mode'
    | '/api/stripe/webhook'
    | '/api/youtube/callback'
    | '/api/youtube/logout'
    | '/api/youtube/me'
    | '/api/youtube/start'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/terms'
    | '/api/pitch'
    | '/api/referrals'
    | '/api/firebase/config'
    | '/api/firebase/custom-token'
    | '/api/firebase/session'
    | '/api/plus/grant'
    | '/api/plus/status'
    | '/api/profile/sync'
    | '/api/stripe/checkout'
    | '/api/stripe/confirm'
    | '/api/stripe/mode'
    | '/api/stripe/webhook'
    | '/api/youtube/callback'
    | '/api/youtube/logout'
    | '/api/youtube/me'
    | '/api/youtube/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiPitchRoute: typeof ApiPitchRoute
  ApiReferralsRoute: typeof ApiReferralsRoute
  ApiFirebaseConfigRoute: typeof ApiFirebaseConfigRoute
  ApiFirebaseCustomTokenRoute: typeof ApiFirebaseCustomTokenRoute
  ApiFirebaseSessionRoute: typeof ApiFirebaseSessionRoute
  ApiPlusGrantRoute: typeof ApiPlusGrantRoute
  ApiPlusStatusRoute: typeof ApiPlusStatusRoute
  ApiProfileSyncRoute: typeof ApiProfileSyncRoute
  ApiStripeCheckoutRoute: typeof ApiStripeCheckoutRoute
  ApiStripeConfirmRoute: typeof ApiStripeConfirmRoute
  ApiStripeModeRoute: typeof ApiStripeModeRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiYoutubeCallbackRoute: typeof ApiYoutubeCallbackRoute
  ApiYoutubeLogoutRoute: typeof ApiYoutubeLogoutRoute
  ApiYoutubeMeRoute: typeof ApiYoutubeMeRoute
  ApiYoutubeStartRoute: typeof ApiYoutubeStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pitch': {
      id: '/api/pitch'
      path: '/api/pitch'
      fullPath: '/api/pitch'
      preLoaderRoute: typeof ApiPitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/referrals': {
      id: '/api/referrals'
      path: '/api/referrals'
      fullPath: '/api/referrals'
      preLoaderRoute: typeof ApiReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/firebase/config': {
      id: '/api/firebase/config'
      path: '/api/firebase/config'
      fullPath: '/api/firebase/config'
      preLoaderRoute: typeof ApiFirebaseConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/firebase/custom-token': {
      id: '/api/firebase/custom-token'
      path: '/api/firebase/custom-token'
      fullPath: '/api/firebase/custom-token'
      preLoaderRoute: typeof ApiFirebaseCustomTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/firebase/session': {
      id: '/api/firebase/session'
      path: '/api/firebase/session'
      fullPath: '/api/firebase/session'
      preLoaderRoute: typeof ApiFirebaseSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plus/grant': {
      id: '/api/plus/grant'
      path: '/api/plus/grant'
      fullPath: '/api/plus/grant'
      preLoaderRoute: typeof ApiPlusGrantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plus/status': {
      id: '/api/plus/status'
      path: '/api/plus/status'
      fullPath: '/api/plus/status'
      preLoaderRoute: typeof ApiPlusStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile/sync': {
      id: '/api/profile/sync'
      path: '/api/profile/sync'
      fullPath: '/api/profile/sync'
      preLoaderRoute: typeof ApiProfileSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/checkout': {
      id: '/api/stripe/checkout'
      path: '/api/stripe/checkout'
      fullPath: '/api/stripe/checkout'
      preLoaderRoute: typeof ApiStripeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/confirm': {
      id: '/api/stripe/confirm'
      path: '/api/stripe/confirm'
      fullPath: '/api/stripe/confirm'
      preLoaderRoute: typeof ApiStripeConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/mode': {
      id: '/api/stripe/mode'
      path: '/api/stripe/mode'
      fullPath: '/api/stripe/mode'
      preLoaderRoute: typeof ApiStripeModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/callback': {
      id: '/api/youtube/callback'
      path: '/api/youtube/callback'
      fullPath: '/api/youtube/callback'
      preLoaderRoute: typeof ApiYoutubeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/logout': {
      id: '/api/youtube/logout'
      path: '/api/youtube/logout'
      fullPath: '/api/youtube/logout'
      preLoaderRoute: typeof ApiYoutubeLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/me': {
      id: '/api/youtube/me'
      path: '/api/youtube/me'
      fullPath: '/api/youtube/me'
      preLoaderRoute: typeof ApiYoutubeMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/start': {
      id: '/api/youtube/start'
      path: '/api/youtube/start'
      fullPath: '/api/youtube/start'
      preLoaderRoute: typeof ApiYoutubeStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiPitchRoute: ApiPitchRoute,
  ApiReferralsRoute: ApiReferralsRoute,
  ApiFirebaseConfigRoute: ApiFirebaseConfigRoute,
  ApiFirebaseCustomTokenRoute: ApiFirebaseCustomTokenRoute,
  ApiFirebaseSessionRoute: ApiFirebaseSessionRoute,
  ApiPlusGrantRoute: ApiPlusGrantRoute,
  ApiPlusStatusRoute: ApiPlusStatusRoute,
  ApiProfileSyncRoute: ApiProfileSyncRoute,
  ApiStripeCheckoutRoute: ApiStripeCheckoutRoute,
  ApiStripeConfirmRoute: ApiStripeConfirmRoute,
  ApiStripeModeRoute: ApiStripeModeRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiYoutubeCallbackRoute: ApiYoutubeCallbackRoute,
  ApiYoutubeLogoutRoute: ApiYoutubeLogoutRoute,
  ApiYoutubeMeRoute: ApiYoutubeMeRoute,
  ApiYoutubeStartRoute: ApiYoutubeStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
